### ISSUE TITLE
Investigate Mastodon's cron job for media removal

### ISSUE THREAD

**Issue by tzouris** [mlaa/commons#558]
Looks like the command is not running.
Will need to install a Messaging Transfer Agent in order to investigate the issue.

**Comment by tzouris** [comment]
Installed postfix to be able to read the output.
The message sent to the local inbox of root says:

> /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/msgpack-1.5.4/lib/msgpack.rb:7:in `require': incompatible library version - /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/msgpack-1.5.4/lib/msgpack/msgpack.so (LoadError)
>         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/msgpack-1.5.4/lib/msgpack.rb:7:in `<top (required)>'
>         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/store.rb:5:in `require'
>         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/store.rb:5:in `block in <top (required)>'
>         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/explicit_require.rb:45:in `rescue in with_gems'
>         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/explicit_require.rb:41:in `with_gems'
>         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/store.rb:5:in `<top (required)>'
>         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache.rb:68:in `require_relative'
>         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache.rb:68:in `<top (required)>'
>         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap.rb:5:in `require_relative'
>         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap.rb:5:in `<top (required)>'
>         from /home/mastodon/live/config/boot.rb:9:in `require'
>         from /home/mastodon/live/config/boot.rb:9:in `<top (required)>'
>         from /home/mastodon/live/bin/tootctl:4:in `require_relative'
>         from /home/mastodon/live/bin/tootctl:4:in `<main>'
> /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/msgpack-1.5.4/lib/msgpack.rb:7:in `require': incompatible library version - /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/msgpack-1.5.4/lib/msgpack/msgpack.so (LoadError)
>         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/msgpack-1.5.4/lib/msgpack.rb:7:in `<top (required)>'
>         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/store.rb:5:in `require'
>         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/store.rb:5:in `block in <top (required)>'
>         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/explicit_require.rb:42:in `with_gems'
>         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/store.rb:5:in `<top (required)>'
>         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache.rb:68:in `require_relative'
>         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache.rb:68:in `<top (required)>'
>         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap.rb:5:in `require_relative'
>         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap.rb:5:in `<top (required)>'
>         from /home/mastodon/live/config/boot.rb:9:in `require'
>         from /home/mastodon/live/config/boot.rb:9:in `<top (required)>'
>         from /home/mastodon/live/bin/tootctl:4:in `require_relative'
>         from /home/mastodon/live/bin/tootctl:4:in `<main>'

Closing the ticket for now since the investigation is over. Manual media removal will continue in the meantime.
New ticket to fix the issue pending.
