### ISSUE TITLE
Mastodon cron job fails to run the media remove command

### ISSUE THREAD

**Issue by tzouris** [mlaa/commons#581]
Other cron tasks run just fine.
No problem running the media remove command manually.

Error message:

```
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/msgpack-1.5.4/lib/msgpack.rb:7:in `require': incompatible library version - /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/msgpack-1.5.4/lib/msgpack/msgpack.so (LoadError)
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/msgpack-1.5.4/lib/msgpack.rb:7:in `<top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/store.rb:5:in `require'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/store.rb:5:in `block in <top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/explicit_require.rb:45:in `rescue in with_gems'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/explicit_require.rb:41:in `with_gems'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/store.rb:5:in `<top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache.rb:68:in `require_relative'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache.rb:68:in `<top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap.rb:5:in `require_relative'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap.rb:5:in `<top (required)>'
        from /home/mastodon/live/config/boot.rb:9:in `require'
        from /home/mastodon/live/config/boot.rb:9:in `<top (required)>'
        from /home/mastodon/live/bin/tootctl:4:in `require_relative'
        from /home/mastodon/live/bin/tootctl:4:in `<main>'
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/msgpack-1.5.4/lib/msgpack.rb:7:in `require': incompatible library version - /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/msgpack-1.5.4/lib/msgpack/msgpack.so (LoadError)
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/msgpack-1.5.4/lib/msgpack.rb:7:in `<top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/store.rb:5:in `require'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/store.rb:5:in `block in <top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/explicit_require.rb:42:in `with_gems'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/store.rb:5:in `<top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache.rb:68:in `require_relative'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache.rb:68:in `<top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap.rb:5:in `require_relative'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap.rb:5:in `<top (required)>'
        from /home/mastodon/live/config/boot.rb:9:in `require'
        from /home/mastodon/live/config/boot.rb:9:in `<top (required)>'
        from /home/mastodon/live/bin/tootctl:4:in `require_relative'
        from /home/mastodon/live/bin/tootctl:4:in `<main>'
```

**Comment by tzouris** [comment]
Turns out that the mastodon user is using .rbenv (installed at `/home/mastodon/.rbenv/shims/ruby`) and the cron uses the root user's version of Ruby (installed at `/usr/bin/ruby`)
Moving issue to Needs Planning for now.

**Comment by tzouris** [comment]
Tried some solutions, but I still get the same error. I'll do more research and re-open the issue. Not important for now, but something it would be nice to have.
